version: '3'

services:
  tic-tac-level3:
    build:
      context: .
    restart: always
    working_dir:  /home/pwn
    container_name: tic-tac3
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9003:9000"
    entrypoint: /etc/init.sh
