version: '3'

services:
  tic-tac-level4:
    build:
      context: .
    restart: always
    working_dir:  /home/pwn
    container_name: tic-tac4
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9004:9000"
    entrypoint: /etc/init.sh
